package POJOs;
// Generated 30/10/2023 10:41:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private Integer idBoleto;
     private Compra compra;
     private Horario horario;
     private Sala sala;
     private Usuario usuarioByUsuarioIngresa;
     private Usuario usuarioByUsuarioModifica;
     private boolean estado;
     private Integer numeroAsiento;
     private Date fechaIngresa;
     private Date fechaModifica;

    public Boleto() {
    }

	
    public Boleto(boolean estado) {
        this.estado = estado;
    }
    public Boleto(Compra compra, Horario horario, Sala sala, Usuario usuarioByUsuarioIngresa, Usuario usuarioByUsuarioModifica, boolean estado, Integer numeroAsiento, Date fechaIngresa, Date fechaModifica) {
       this.compra = compra;
       this.horario = horario;
       this.sala = sala;
       this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.numeroAsiento = numeroAsiento;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
    }
   
    public Integer getIdBoleto() {
        return this.idBoleto;
    }
    
    public void setIdBoleto(Integer idBoleto) {
        this.idBoleto = idBoleto;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Usuario getUsuarioByUsuarioIngresa() {
        return this.usuarioByUsuarioIngresa;
    }
    
    public void setUsuarioByUsuarioIngresa(Usuario usuarioByUsuarioIngresa) {
        this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Integer getNumeroAsiento() {
        return this.numeroAsiento;
    }
    
    public void setNumeroAsiento(Integer numeroAsiento) {
        this.numeroAsiento = numeroAsiento;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


