package POJOs;
// Generated 30/10/2023 10:41:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clasificacion generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer idClasificacion;
     private Usuario usuarioByUsuarioIngresa;
     private Usuario usuarioByUsuarioModifica;
     private String clasificacion;
     private Date fechaIngresa;
     private Date fechaModifica;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Clasificacion() {
    }

    public Clasificacion(Usuario usuarioByUsuarioIngresa, Usuario usuarioByUsuarioModifica, String clasificacion, Date fechaIngresa, Date fechaModifica, Set<Pelicula> peliculas) {
       this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.clasificacion = clasificacion;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
       this.peliculas = peliculas;
    }
   
    public Integer getIdClasificacion() {
        return this.idClasificacion;
    }
    
    public void setIdClasificacion(Integer idClasificacion) {
        this.idClasificacion = idClasificacion;
    }
    public Usuario getUsuarioByUsuarioIngresa() {
        return this.usuarioByUsuarioIngresa;
    }
    
    public void setUsuarioByUsuarioIngresa(Usuario usuarioByUsuarioIngresa) {
        this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


