package POJOs;
// Generated 30/10/2023 10:41:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Cliente cliente;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngresa;
     private boolean estado;
     private Date fechaCompra;
     private BigDecimal totalCompra;
     private Date fechaIngresa;
     private Date fechaModifica;
     private Set<Boleto> boletos = new HashSet<Boleto>(0);

    public Compra() {
    }

	
    public Compra(boolean estado) {
        this.estado = estado;
    }
    public Compra(Cliente cliente, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngresa, boolean estado, Date fechaCompra, BigDecimal totalCompra, Date fechaIngresa, Date fechaModifica, Set<Boleto> boletos) {
       this.cliente = cliente;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
       this.estado = estado;
       this.fechaCompra = fechaCompra;
       this.totalCompra = totalCompra;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
       this.boletos = boletos;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngresa() {
        return this.usuarioByUsuarioIngresa;
    }
    
    public void setUsuarioByUsuarioIngresa(Usuario usuarioByUsuarioIngresa) {
        this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public BigDecimal getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(BigDecimal totalCompra) {
        this.totalCompra = totalCompra;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set<Boleto> getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set<Boleto> boletos) {
        this.boletos = boletos;
    }




}


