package POJOs;
// Generated 30/10/2023 10:41:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private Usuario usuarioByUsuarioIngresa;
     private Usuario usuarioByUsuarioModifica;
     private String genero;
     private Date fechaIngresa;
     private Date fechaModifica;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Genero() {
    }

    public Genero(Usuario usuarioByUsuarioIngresa, Usuario usuarioByUsuarioModifica, String genero, Date fechaIngresa, Date fechaModifica, Set<Pelicula> peliculas) {
       this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.genero = genero;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
       this.peliculas = peliculas;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public Usuario getUsuarioByUsuarioIngresa() {
        return this.usuarioByUsuarioIngresa;
    }
    
    public void setUsuarioByUsuarioIngresa(Usuario usuarioByUsuarioIngresa) {
        this.usuarioByUsuarioIngresa = usuarioByUsuarioIngresa;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


