package POJOs;
// Generated 30/10/2023 10:41:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private boolean estado;
     private String nombrePerfil;
     private String descripcion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfil() {
    }

	
    public Perfil(boolean estado) {
        this.estado = estado;
    }
    public Perfil(boolean estado, String nombrePerfil, String descripcion, Set<Usuario> usuarios) {
       this.estado = estado;
       this.nombrePerfil = nombrePerfil;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getNombrePerfil() {
        return this.nombrePerfil;
    }
    
    public void setNombrePerfil(String nombrePerfil) {
        this.nombrePerfil = nombrePerfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


